CREATE TABLE `core_user_master` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `role_id` int(11) DEFAULT NULL,
  `login` varchar(150) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `identification_number` varchar(50) DEFAULT NULL,
  `title_id` int(11) DEFAULT NULL,
  `session_id` varchar(32) DEFAULT NULL,
  `workspace_id` int(11) DEFAULT NULL,
  `teamspace_id` int(11) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `photograph` blob,
  `photograph_thumb` blob,
  `photograph_filename` varchar(255) DEFAULT NULL,
  `photograph_filesize` int(11) DEFAULT NULL,
  `photograph_type` varchar(30) DEFAULT NULL,
  `photograph_thumb_filename` varchar(255) DEFAULT NULL,
  `photograph_thumb_filesize` int(11) DEFAULT NULL,
  `photograph_thumb_type` varchar(30) DEFAULT NULL,
  `email_primary` varchar(100) DEFAULT NULL,
  `email_secondary` varchar(100) DEFAULT NULL,
  `timezone` float DEFAULT NULL,
  `logged_in` char(1) DEFAULT 'n',
  `country_id` int(11) DEFAULT NULL,
  `language` char(2) DEFAULT 'en',
  `activated` char(1) DEFAULT 'n',
  `activation_code` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  KEY `role_id` (`role_id`),
  KEY `title_id` (`title_id`),
  KEY `session_id` (`session_id`),
  KEY `workspace_id` (`workspace_id`),
  KEY `teamspace_id` (`teamspace_id`),
  KEY `country_id` (`country_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1