CREATE TABLE `helpdesk_tickets` (
  `ticket_id` int(5) NOT NULL AUTO_INCREMENT,
  `workspace_id` int(5) DEFAULT NULL,
  `teamspace_id` int(5) DEFAULT NULL,
  `category_id` int(5) DEFAULT NULL,
  `priority_id` int(5) DEFAULT NULL,
  `location_id` int(5) DEFAULT NULL,
  `status_id` int(5) DEFAULT NULL,
  `user_id_logging` int(5) DEFAULT NULL,
  `user_id_problem` int(5) DEFAULT NULL,
  `user_problem_name` varchar(255) DEFAULT NULL,
  `user_problem_contact_tel_no` varchar(255) DEFAULT NULL,
  `user_problem_contact_email` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `technical_description` text,
  `solution` text,
  `technical_solution` text,
  `date_submit` datetime DEFAULT NULL,
  `date_start_work` datetime DEFAULT NULL,
  `date_estimated_completion` datetime DEFAULT NULL,
  `date_complete` datetime DEFAULT NULL,
  `feedback_id` int(5) DEFAULT NULL,
  `review_id` int(5) DEFAULT NULL,
  `feedback_comments` text,
  `review_comments` text,
  `significance_id` int(5) DEFAULT NULL,
  `estimate_time_spent` int(5) DEFAULT NULL,
  `actual_time_spent` int(5) DEFAULT NULL,
  `date_due` datetime DEFAULT NULL,
  `date_last_edit` datetime DEFAULT NULL,
  `submit_month` tinyint(2) DEFAULT NULL,
  `duplicate_ticket` char(1) DEFAULT 'n',
  PRIMARY KEY (`ticket_id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8